

services:
  # Servicio de MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Servicio del Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8000:5000"  # Cambiado de 5000:5000 a 8000:5000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/planning-center-clone
      - JWT_SECRET=secreto_super_seguro_para_docker
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
    networks:
      - app-network

  # Servicio del Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api  # Actualizado para usar el puerto 8000
    networks:
      - app-network

# Volúmenes
volumes:
  mongodb_data:

# Redes
networks:
  app-network:
    driver: bridge