FROM node:16-alpine

# Crear directorio de trabajo
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias de producción (no incluye devDependencies)
RUN npm ci --only=production

# Copiar el código fuente
COPY . .

# Exponer puerto
EXPOSE 5000

# Establecer NODE_ENV a producción
ENV NODE_ENV production

# Comando para iniciar la aplicación
CMD ["node", "server.js"]